sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arun/react-test npm test

after_success:
  - docker build -t arun/multi-client ./client
  - docker build -t arun/multi-nginx ./nginx
  - docker build -t arun/multi-server ./server
  - docker build -t arun/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all multi  images and push them to docker hub
  - docker push arun/multi-client
  - docker push arun/multi-nginx
  - docker push arun/multi-server
  - docker push arun/multi-worker

 ## Deploying multi container to AWS 
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
